// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQka3gwc8WWZYIvjlL2CtMlqgmAMJVtI4',
    appId: '1:786237363860:web:53029f916aac59d0524681',
    messagingSenderId: '786237363860',
    projectId: 'jobnumber-f871d',
    authDomain: 'jobnumber-f871d.firebaseapp.com',
    storageBucket: 'jobnumber-f871d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkDMQKyiCLhR1z9S3-d9jloOG9WBug9qI',
    appId: '1:786237363860:android:50590d049ab27fcc524681',
    messagingSenderId: '786237363860',
    projectId: 'jobnumber-f871d',
    storageBucket: 'jobnumber-f871d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIIJaDGtHYgseKJ0r_PsvqVIP8cgXFPkw',
    appId: '1:786237363860:ios:45a186ce6caf2e4d524681',
    messagingSenderId: '786237363860',
    projectId: 'jobnumber-f871d',
    storageBucket: 'jobnumber-f871d.firebasestorage.app',
    iosBundleId: 'com.example.jobNumber01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIIJaDGtHYgseKJ0r_PsvqVIP8cgXFPkw',
    appId: '1:786237363860:ios:45a186ce6caf2e4d524681',
    messagingSenderId: '786237363860',
    projectId: 'jobnumber-f871d',
    storageBucket: 'jobnumber-f871d.firebasestorage.app',
    iosBundleId: 'com.example.jobNumber01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQka3gwc8WWZYIvjlL2CtMlqgmAMJVtI4',
    appId: '1:786237363860:web:5d189e06c0fe6408524681',
    messagingSenderId: '786237363860',
    projectId: 'jobnumber-f871d',
    authDomain: 'jobnumber-f871d.firebaseapp.com',
    storageBucket: 'jobnumber-f871d.firebasestorage.app',
  );

}